#!/usr/bin/env bash

# Generated by scripts/build.sh. Edit src/* instead.


set -euo pipefail

readonly VERSION="2.0.0" # x-release-please-version
readonly UPDATE_REPO_OWNER="botjaeger"
readonly UPDATE_REPO_NAME="claude-switch"
readonly UPDATE_RELEASE_API_URL="https://api.github.com/repos/${UPDATE_REPO_OWNER}/${UPDATE_REPO_NAME}/releases/latest"
readonly STATE_DIR="$HOME/.claude-switch"
readonly MANIFEST_FILE="$STATE_DIR/manifest.json"
readonly CONFIGS_DIR="$STATE_DIR/configs"
readonly PROFILES_DIR="$STATE_DIR/profiles"
readonly LEGACY_BACKUP_DIR="$HOME/.claude-switch-backup"
readonly LEGACY_SEQUENCE_FILE="$LEGACY_BACKUP_DIR/sequence.json"
readonly LINUX_STORE_SERVICE="claude-switch-v2"
readonly LEGACY_LINUX_SERVICE="claude-code"
readonly WSL_ACTIVE_STORE_BASENAME="active-credentials.enc"
readonly WSL_STORE_DIR_NAME=".claude-switch-v2"
readonly LEGACY_WSL_STORE_DIR_NAME=".claude-switch"

GLOBAL_YES=false
INTERACTIVE_FORCE="${CLAUDE_SWITCH_FORCE_INTERACTIVE:-0}"
PLATFORM_CACHE=""
SPINNER_PID=""
SPINNER_CHARS=( "|" "/" "-" "\\" )

trap 'spinner_stop' EXIT

in_container() {
    if [[ -f /.dockerenv ]]; then
        return 0
    fi
    if [[ -f /proc/1/cgroup ]] && grep -q 'docker\|lxc\|containerd\|kubepods' /proc/1/cgroup 2>/dev/null; then
        return 0
    fi
    if [[ -f /proc/self/mountinfo ]] && grep -q 'docker\|overlay' /proc/self/mountinfo 2>/dev/null; then
        return 0
    fi
    if [[ -n "${CONTAINER:-}" ]] || [[ -n "${container:-}" ]]; then
        return 0
    fi
    return 1
}

detect_platform() {
    if [[ -n "$PLATFORM_CACHE" ]]; then
        echo "$PLATFORM_CACHE"
        return 0
    fi
    case "$(uname -s)" in
        Darwin) PLATFORM_CACHE="macos" ;;
        Linux)
            if [[ -n "${WSL_DISTRO_NAME:-}" ]]; then
                PLATFORM_CACHE="wsl"
            else
                PLATFORM_CACHE="linux"
            fi
            ;;
        *) PLATFORM_CACHE="unknown" ;;
    esac
    echo "$PLATFORM_CACHE"
}

iso8601_now() {
    date -u +%Y-%m-%dT%H:%M:%SZ
}

error() {
    echo "Error: $*" >&2
}

warn() {
    echo "Warning: $*" >&2
}

sanitize_slug() {
    local value="$1"
    value=$(printf '%s' "$value" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9._-]+/-/g; s/^-+//; s/-+$//; s/-+/-/g')
    if [[ -z "$value" ]]; then
        value="item"
    fi
    echo "$value"
}

validate_json_file() {
    local file="$1"
    jq . "$file" >/dev/null 2>&1
}

validate_email() {
    local email="$1"
    [[ "$email" =~ ^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$ ]]
}

validate_alias() {
    local alias="$1"
    if [[ ! "$alias" =~ ^[A-Za-z0-9_-]+$ ]]; then
        return 1
    fi
    if [[ "$alias" =~ ^[0-9]+$ ]]; then
        return 1
    fi
    if validate_email "$alias"; then
        return 1
    fi
    return 0
}

require_command() {
    local cmd="$1"
    if ! command -v "$cmd" >/dev/null 2>&1; then
        error "Required command '$cmd' not found"
        return 1
    fi
    return 0
}

ensure_dir_secure() {
    local dir="$1"
    mkdir -p "$dir"
    chmod 700 "$dir"
}

write_json() {
    local file="$1"
    local content="$2"
    local tmp

    tmp=$(mktemp "${file}.XXXXXX")
    printf '%s\n' "$content" > "$tmp"
    if ! jq . "$tmp" >/dev/null 2>&1; then
        rm -f "$tmp"
        error "Generated invalid JSON for $file"
        return 1
    fi
    chmod 600 "$tmp"
    mv "$tmp" "$file"
}

copy_json_file_secure() {
    local src="$1"
    local dest="$2"
    local content
    if [[ ! -f "$src" ]]; then
        error "Missing JSON file: $src"
        return 1
    fi
    if ! validate_json_file "$src"; then
        error "Invalid JSON in $src"
        return 1
    fi
    content=$(<"$src")
    write_json "$dest" "$content"
}

copy_tree_secure() {
    local src="$1"
    local dest="$2"
    mkdir -p "$dest"
    if [[ -d "$src" ]]; then
        cp -R "$src"/. "$dest"/
    fi
    find "$dest" -type d -exec chmod 700 {} + 2>/dev/null || true
    find "$dest" -type f -exec chmod 600 {} + 2>/dev/null || true
}

check_bash_version() {
    local version
    version=$(bash --version | head -n1 | grep -oE '[0-9]+\.[0-9]+' | head -n1)
    if ! awk -v ver="$version" 'BEGIN { exit (ver >= 4.4 ? 0 : 1) }'; then
        error "Bash 4.4+ required (found $version)"
        return 1
    fi
    return 0
}

state_dirs_init() {
    ensure_dir_secure "$STATE_DIR"
    ensure_dir_secure "$CONFIGS_DIR"
    ensure_dir_secure "$PROFILES_DIR"
}

manifest_exists() {
    [[ -f "$MANIFEST_FILE" ]]
}

legacy_state_exists() {
    [[ -f "$LEGACY_SEQUENCE_FILE" ]]
}

manifest_default_json() {
    local now
    now=$(iso8601_now)
    jq -n --arg now "$now" '
        {
            schemaVersion: 2,
            createdAt: $now,
            lastUpdated: $now,
            importedLegacy: false,
            activeAccountId: null,
            order: [],
            accounts: {}
        }
    '
}

manifest_init_empty() {
    state_dirs_init
    if [[ ! -f "$MANIFEST_FILE" ]]; then
        write_json "$MANIFEST_FILE" "$(manifest_default_json)"
    fi
}

manifest_assert_valid() {
    if [[ ! -f "$MANIFEST_FILE" ]]; then
        error "No v2 state found"
        return 1
    fi
    if ! validate_json_file "$MANIFEST_FILE"; then
        error "Invalid JSON in $MANIFEST_FILE"
        return 1
    fi
    if ! jq -e '.schemaVersion == 2 and (.accounts | type == "object") and (.order | type == "array")' "$MANIFEST_FILE" >/dev/null 2>&1; then
        error "Unsupported or invalid manifest format"
        return 1
    fi
    return 0
}

manifest_account_count() {
    if ! manifest_exists; then
        echo "0"
        return 0
    fi
    jq -r '.order | length' "$MANIFEST_FILE" 2>/dev/null || echo "0"
}

get_claude_config_path() {
    local primary="$HOME/.claude/.claude.json"
    local fallback="$HOME/.claude.json"

    if [[ -f "$primary" ]] && jq -e '.oauthAccount' "$primary" >/dev/null 2>&1; then
        echo "$primary"
        return 0
    fi
    echo "$fallback"
}

read_current_global_email() {
    local config
    config=$(get_claude_config_path)
    if [[ ! -f "$config" ]]; then
        echo "none"
        return 0
    fi
    if ! validate_json_file "$config"; then
        echo "none"
        return 0
    fi
    jq -r '.oauthAccount.emailAddress // "none"' "$config" 2>/dev/null
}

current_oauth_uuid() {
    local config
    config=$(get_claude_config_path)
    if [[ ! -f "$config" ]]; then
        echo ""
        return 0
    fi
    jq -r '.oauthAccount.accountUuid // empty' "$config" 2>/dev/null
}

generate_account_id() {
    local email="$1"
    printf 'acct-%s-%04d-%s\n' "$(date -u +%Y%m%d%H%M%S)" "$RANDOM" "$(sanitize_slug "$email")"
}

pretty_path() {
    local path="$1"
    if [[ "$path" == "$HOME"* ]]; then
        echo "~${path#"$HOME"}"
    else
        echo "$path"
    fi
}

replace_with_symlink() {
    local source="$1"
    local target="$2"

    if [[ -L "$target" ]] && [[ "$(readlink "$target")" == "$source" ]]; then
        return 0
    fi

    rm -rf "$target"
    ln -s "$source" "$target"
}

link_shared_user_scope_into_profile() {
    local profile_dir="$1"
    local source_root="$HOME/.claude"
    local item source target

    for item in settings.json agents commands hooks skills plugins agent-memory; do
        source="$source_root/$item"
        target="$profile_dir/$item"

        if [[ ! -e "$source" ]]; then
            continue
        fi

        if [[ -d "$source" ]]; then
            if [[ -L "$target" ]]; then
                if [[ "$(readlink "$target")" == "$source" ]]; then
                    continue
                fi
                rm -rf "$target"
            elif [[ ! -e "$target" ]]; then
                ln -s "$source" "$target"
                continue
            elif [[ ! -d "$target" ]]; then
                replace_with_symlink "$source" "$target"
                continue
            fi

            local source_item target_item
            for source_item in "$source"/* "$source"/.[!.]* "$source"/..?*; do
                [[ -e "$source_item" ]] || continue
                target_item="$target/$(basename "$source_item")"
                replace_with_symlink "$source_item" "$target_item"
            done
            continue
        fi

        replace_with_symlink "$source" "$target"
    done
}

claude_project_store_key() {
    local project_path="${1:-$(pwd)}"
    printf '%s' "$project_path" | sed 's|/|-|g'
}

link_current_project_memory_into_profile() {
    local profile_dir="$1"
    local project_key source_dir target_dir target_parent

    project_key=$(claude_project_store_key "$(pwd)")
    source_dir="$HOME/.claude/projects/$project_key/memory"
    if [[ ! -d "$source_dir" ]]; then
        return 0
    fi

    target_dir="$profile_dir/projects/$project_key/memory"
    target_parent=$(dirname "$target_dir")
    mkdir -p "$target_parent"
    chmod 700 "$profile_dir/projects" "$target_parent" 2>/dev/null || true

    if [[ -L "$target_dir" ]]; then
        if [[ "$(readlink "$target_dir")" == "$source_dir" ]]; then
            return 0
        fi
        rm -rf "$target_dir"
    elif [[ ! -e "$target_dir" ]]; then
        ln -s "$source_dir" "$target_dir"
        return 0
    elif [[ ! -d "$target_dir" ]]; then
        replace_with_symlink "$source_dir" "$target_dir"
        return 0
    fi

    local source_item target_item
    for source_item in "$source_dir"/* "$source_dir"/.[!.]* "$source_dir"/..?*; do
        [[ -e "$source_item" ]] || continue
        target_item="$target_dir/$(basename "$source_item")"
        replace_with_symlink "$source_item" "$target_item"
    done
}

pause_for_enter() {
    echo ""
    echo -n "Press Enter to continue..." >&2
    IFS= read -r _ || true
}

prompt_line() {
    local prompt="$1"
    local reply
    echo -n "$prompt" >&2
    IFS= read -r reply || true
    echo "$reply"
}

prompt_yes_no() {
    local prompt="$1"
    local reply
    echo -n "$prompt [y/N] " >&2
    IFS= read -r reply || true
    [[ "$reply" == "y" || "$reply" == "Y" ]]
}

clear_screen() {
    if [[ -t 1 ]] && command -v clear >/dev/null 2>&1; then
        clear
    fi
}

spinner_start() {
    local message="$1"
    (
        while true; do
            local char
            for char in "${SPINNER_CHARS[@]}"; do
                printf '\r%s %s' "$char" "$message"
                sleep 0.1
            done
        done
    ) &
    SPINNER_PID=$!
}

spinner_stop() {
    if [[ -n "$SPINNER_PID" ]]; then
        kill "$SPINNER_PID" 2>/dev/null || true
        wait "$SPINNER_PID" 2>/dev/null || true
        SPINNER_PID=""
        printf '\r\033[K'
    fi
}

format_duration() {
    local seconds="$1"
    if [[ "$seconds" -le 0 ]]; then
        echo "now"
        return 0
    fi
    local days hours minutes
    local parts=()

    days=$((seconds / 86400))
    hours=$(((seconds % 86400) / 3600))
    minutes=$(((seconds % 3600) / 60))
    [[ "$days" -gt 0 ]] && parts+=("${days}d")
    [[ "$hours" -gt 0 ]] && parts+=("${hours}h")
    [[ "$days" -eq 0 && "$minutes" -gt 0 ]] && parts+=("${minutes}m")
    printf '%s\n' "${parts[*]}"
}

parse_reset_time_epoch() {
    local ts="$1"
    local epoch=""
    epoch=$(date -u -jf "%Y-%m-%dT%H:%M:%S" "${ts%%.*}" +%s 2>/dev/null) || \
    epoch=$(date -d "$ts" +%s 2>/dev/null) || epoch=""
    echo "$epoch"
}

needs_sudo() {
    local dir="$1"
    [[ ! -w "$dir" ]]
}

run_maybe_sudo() {
    local dir="$1"
    shift
    if needs_sudo "$dir"; then
        sudo "$@"
    else
        "$@"
    fi
}

current_macos_global_service() {
    if security find-generic-password -s "Claude Code-credentials" >/dev/null 2>&1; then
        echo "Claude Code-credentials"
        return 0
    fi
    if security find-generic-password -s "Claude Code" >/dev/null 2>&1; then
        echo "Claude Code"
        return 0
    fi
    echo ""
}

wsl_store_dir() {
    local basename="$1"
    local win_profile
    local wsl_profile

    win_profile=$(powershell.exe -NoProfile -Command '[Environment]::GetFolderPath("UserProfile")' 2>/dev/null | tr -d '\r')
    wsl_profile=$(wslpath -u "$win_profile" 2>/dev/null)
    printf '%s/%s\n' "$wsl_profile" "$basename"
}

wsl_encrypt_to_file() {
    local plaintext="$1"
    local output_file="$2"
    local dir tmp_plain win_tmp win_out

    dir=$(dirname "$output_file")
    mkdir -p "$dir"
    chmod 700 "$dir"
    tmp_plain=$(mktemp "${dir}/.tmp-plain-XXXXXX")
    printf '%s' "$plaintext" > "$tmp_plain"
    chmod 600 "$tmp_plain"
    win_tmp=$(wslpath -w "$tmp_plain" 2>/dev/null)
    win_out=$(wslpath -w "$output_file" 2>/dev/null)
    powershell.exe -NoProfile -Command "
        Add-Type -AssemblyName System.Security
        \$bytes = [IO.File]::ReadAllBytes('${win_tmp}')
        Remove-Item -LiteralPath '${win_tmp}' -Force
        \$enc = [Security.Cryptography.ProtectedData]::Protect(\$bytes, \$null, 'CurrentUser')
        [IO.File]::WriteAllBytes('${win_out}', \$enc)
    " >/dev/null 2>&1
    rm -f "$tmp_plain" 2>/dev/null || true
}

wsl_decrypt_file() {
    local input_file="$1"
    local win_path

    if [[ ! -f "$input_file" ]]; then
        echo ""
        return 0
    fi
    win_path=$(wslpath -w "$input_file" 2>/dev/null)
    if [[ -z "$win_path" ]]; then
        echo ""
        return 0
    fi
    powershell.exe -NoProfile -Command "
        Add-Type -AssemblyName System.Security
        \$bytes = [IO.File]::ReadAllBytes('${win_path}')
        \$plain = [Security.Cryptography.ProtectedData]::Unprotect(\$bytes, \$null, 'CurrentUser')
        [Text.Encoding]::UTF8.GetString(\$plain)
    " 2>/dev/null | tr -d '\r'
}

wsl_delete_file() {
    local input_file="$1"
    local win_path

    if [[ ! -f "$input_file" ]]; then
        return 0
    fi
    win_path=$(wslpath -w "$input_file" 2>/dev/null)
    if [[ -z "$win_path" ]]; then
        rm -f "$input_file"
        return 0
    fi
    powershell.exe -NoProfile -Command "Remove-Item -LiteralPath '${win_path}' -Force" >/dev/null 2>&1 || true
}

global_credentials_read() {
    local platform
    platform=$(detect_platform)
    case "$platform" in
        macos)
            local service
            service=$(current_macos_global_service)
            if [[ -n "$service" ]]; then
                security find-generic-password -s "$service" -w 2>/dev/null || echo ""
            else
                echo ""
            fi
            ;;
        linux)
            secret-tool lookup service "$LEGACY_LINUX_SERVICE" type "active-credentials" 2>/dev/null || echo ""
            ;;
        wsl)
            wsl_decrypt_file "$(wsl_store_dir "$WSL_STORE_DIR_NAME")/$WSL_ACTIVE_STORE_BASENAME"
            ;;
        *)
            echo ""
            ;;
    esac
}

global_credentials_write() {
    local credentials="$1"
    local platform
    platform=$(detect_platform)
    case "$platform" in
        macos)
            local service
            service=$(current_macos_global_service)
            if [[ -z "$service" ]]; then
                service="Claude Code-credentials"
            fi
            security add-generic-password -U -s "$service" -a "$USER" -w "$credentials" >/dev/null 2>&1
            ;;
        linux)
            printf '%s' "$credentials" | secret-tool store --label="Claude Code Active Credentials" \
                service "$LEGACY_LINUX_SERVICE" type "active-credentials" >/dev/null 2>&1
            ;;
        wsl)
            wsl_encrypt_to_file "$credentials" "$(wsl_store_dir "$WSL_STORE_DIR_NAME")/$WSL_ACTIVE_STORE_BASENAME"
            ;;
        *)
            return 1
            ;;
    esac
}

stored_account_credentials_read() {
    local account_id="$1"
    local email="$2"
    local platform
    platform=$(detect_platform)
    case "$platform" in
        macos)
            security find-generic-password -s "claude-switch-v2-account-${account_id}" -a "$email" -w 2>/dev/null || echo ""
            ;;
        linux)
            secret-tool lookup service "$LINUX_STORE_SERVICE" type "account-credentials" account_id "$account_id" email "$email" 2>/dev/null || echo ""
            ;;
        wsl)
            wsl_decrypt_file "$(wsl_store_dir "$WSL_STORE_DIR_NAME")/account-${account_id}.enc"
            ;;
        *)
            echo ""
            ;;
    esac
}

stored_account_credentials_write() {
    local account_id="$1"
    local email="$2"
    local credentials="$3"
    local platform
    platform=$(detect_platform)
    case "$platform" in
        macos)
            security add-generic-password -U -s "claude-switch-v2-account-${account_id}" -a "$email" -w "$credentials" >/dev/null 2>&1
            ;;
        linux)
            printf '%s' "$credentials" | secret-tool store --label="claude-switch v2 ${email}" \
                service "$LINUX_STORE_SERVICE" type "account-credentials" account_id "$account_id" email "$email" >/dev/null 2>&1
            ;;
        wsl)
            wsl_encrypt_to_file "$credentials" "$(wsl_store_dir "$WSL_STORE_DIR_NAME")/account-${account_id}.enc"
            ;;
        *)
            return 1
            ;;
    esac
}

stored_account_credentials_delete() {
    local account_id="$1"
    local email="$2"
    local platform
    platform=$(detect_platform)
    case "$platform" in
        macos)
            security delete-generic-password -s "claude-switch-v2-account-${account_id}" -a "$email" >/dev/null 2>&1 || true
            ;;
        linux)
            secret-tool clear service "$LINUX_STORE_SERVICE" type "account-credentials" account_id "$account_id" email "$email" >/dev/null 2>&1 || true
            ;;
        wsl)
            wsl_delete_file "$(wsl_store_dir "$WSL_STORE_DIR_NAME")/account-${account_id}.enc"
            ;;
    esac
}

legacy_account_credentials_read() {
    local legacy_number="$1"
    local email="$2"
    local platform
    platform=$(detect_platform)
    case "$platform" in
        macos)
            security find-generic-password -s "Claude Code-Account-${legacy_number}-${email}" -w 2>/dev/null || echo ""
            ;;
        linux)
            secret-tool lookup service "$LEGACY_LINUX_SERVICE" account "$legacy_number" email "$email" 2>/dev/null || echo ""
            ;;
        wsl)
            wsl_decrypt_file "$(wsl_store_dir "$LEGACY_WSL_STORE_DIR_NAME")/account-${legacy_number}-${email}.enc"
            ;;
        *)
            echo ""
            ;;
    esac
}

backend_requirements_for() {
    local command_name="$1"
    case "$command_name" in
        add|switch|status|whoami|import-legacy)
            ;;
        *)
            return 0
            ;;
    esac

    case "$(detect_platform)" in
        linux)
            require_command secret-tool || return 1
            ;;
        wsl)
            require_command powershell.exe || return 1
            require_command wslpath || return 1
            ;;
    esac
    return 0
}

legacy_profile_dir_for() {
    local legacy_number="$1"
    local email="$2"
    printf '%s/profiles/account-%s-%s\n' "$LEGACY_BACKUP_DIR" "$legacy_number" "$(sanitize_slug "$email")"
}

state_account_config_path() {
    local account_id="$1"
    jq -r --arg id "$account_id" '.accounts[$id].configFile // empty' "$MANIFEST_FILE" | sed "s|^|$STATE_DIR/|"
}

state_account_profile_path() {
    local account_id="$1"
    jq -r --arg id "$account_id" '.accounts[$id].profileDir // empty' "$MANIFEST_FILE" | sed "s|^|$STATE_DIR/|"
}

state_account_email() {
    local account_id="$1"
    jq -r --arg id "$account_id" '.accounts[$id].email // empty' "$MANIFEST_FILE"
}

state_account_alias() {
    local account_id="$1"
    jq -r --arg id "$account_id" '.accounts[$id].alias // empty' "$MANIFEST_FILE"
}

state_account_exists_by_email() {
    local email="$1"
    jq -e --arg email "$email" '.accounts | to_entries[] | select(.value.email == $email)' "$MANIFEST_FILE" >/dev/null 2>&1
}

state_find_account_id() {
    local identifier="$1"
    local account_id
    account_id=$(jq -r --arg email "$identifier" '.accounts | to_entries[] | select(.value.email == $email) | .key' "$MANIFEST_FILE" 2>/dev/null | head -n1)
    if [[ -n "$account_id" && "$account_id" != "null" ]]; then
        echo "$account_id"
        return 0
    fi
    account_id=$(jq -r --arg alias "$identifier" '.accounts | to_entries[] | select(.value.alias == $alias) | .key' "$MANIFEST_FILE" 2>/dev/null | head -n1)
    if [[ -n "$account_id" && "$account_id" != "null" ]]; then
        echo "$account_id"
        return 0
    fi
    echo ""
}

state_current_active_managed_id() {
    local current_email
    current_email=$(read_current_global_email)
    if [[ "$current_email" == "none" ]]; then
        echo ""
        return 0
    fi
    state_find_account_id "$current_email"
}

state_write_manifest_jq() {
    local filter="${!#}"
    local args=("${@:1:$(($# - 1))}")
    local tmp

    tmp=$(mktemp "${MANIFEST_FILE}.XXXXXX")
    if ! jq "${args[@]}" "$filter" "$MANIFEST_FILE" > "$tmp"; then
        rm -f "$tmp"
        error "Failed to update manifest"
        return 1
    fi
    chmod 600 "$tmp"
    mv "$tmp" "$MANIFEST_FILE"
}

state_add_account_record() {
    local account_id="$1"
    local email="$2"
    local uuid="$3"
    local alias_name="$4"
    local config_rel="$5"
    local profile_rel="$6"
    local imported_from="$7"
    local now
    now=$(iso8601_now)

    # shellcheck disable=SC2016  # jq filter references $id/$email/etc via --arg, not shell expansion
    state_write_manifest_jq \
        --arg id "$account_id" \
        --arg email "$email" \
        --arg uuid "$uuid" \
        --arg alias "$alias_name" \
        --arg configFile "$config_rel" \
        --arg profileDir "$profile_rel" \
        --arg importedFrom "$imported_from" \
        --arg now "$now" '
        .accounts[$id] = (
            {
                id: $id,
                email: $email,
                configFile: $configFile,
                profileDir: $profileDir,
                createdAt: $now,
                updatedAt: $now
            } +
            (if ($uuid | length) > 0 then {uuid: $uuid} else {} end) +
            (if ($alias | length) > 0 then {alias: $alias} else {} end) +
            (if ($importedFrom | length) > 0 then {importedFrom: $importedFrom} else {} end)
        ) |
        .order += [$id] |
        .lastUpdated = $now
        '
}

state_set_alias() {
    local account_id="$1"
    local alias_name="$2"
    local now
    now=$(iso8601_now)
    # shellcheck disable=SC2016  # jq filter references $id/$alias/$now via --arg, not shell expansion
    state_write_manifest_jq \
        --arg id "$account_id" \
        --arg alias "$alias_name" \
        --arg now "$now" '
        .accounts[$id].alias = $alias |
        .accounts[$id].updatedAt = $now |
        .lastUpdated = $now
        '
}

state_remove_alias() {
    local account_id="$1"
    local now
    now=$(iso8601_now)
    # shellcheck disable=SC2016  # jq filter references $id/$now via --arg, not shell expansion
    state_write_manifest_jq \
        --arg id "$account_id" \
        --arg now "$now" '
        .accounts[$id] |= del(.alias) |
        .accounts[$id].updatedAt = $now |
        .lastUpdated = $now
        '
}

state_set_active_account() {
    local account_id="$1"
    local now
    now=$(iso8601_now)
    # shellcheck disable=SC2016  # jq filter references $id/$now via --arg, not shell expansion
    state_write_manifest_jq \
        --arg id "$account_id" \
        --arg now "$now" '
        .activeAccountId = $id |
        .lastUpdated = $now
        '
}

state_remove_account_record() {
    local account_id="$1"
    local now
    now=$(iso8601_now)
    # shellcheck disable=SC2016  # jq filter references $id/$now via --arg, not shell expansion
    state_write_manifest_jq \
        --arg id "$account_id" \
        --arg now "$now" '
        del(.accounts[$id]) |
        .order = [.order[] | select(. != $id)] |
        .activeAccountId = (if .activeAccountId == $id then null else .activeAccountId end) |
        .lastUpdated = $now
        '
}

state_alias_in_use_by_other() {
    local alias_name="$1"
    local account_id="$2"
    local other_id
    other_id=$(jq -r --arg alias "$alias_name" '.accounts | to_entries[] | select(.value.alias == $alias) | .key' "$MANIFEST_FILE" 2>/dev/null | head -n1)
    if [[ -n "$other_id" && "$other_id" != "null" && "$other_id" != "$account_id" ]]; then
        echo "$other_id"
        return 0
    fi
    echo ""
}

state_list_render() {
    local active_id
    active_id=$(state_current_active_managed_id)
    jq -r --arg active "$active_id" '
        if (.order | length) == 0 then
            ""
        else
            .order[] as $id |
            .accounts[$id] |
            "  \(.email)" +
            (if .alias then " [\(.alias)]" else "" end) +
            (if $id == $active then " (active)" else "" end)
        end
    ' "$MANIFEST_FILE"
}

save_account_config_snapshot() {
    local source_config="$1"
    local dest="$2"
    copy_json_file_secure "$source_config" "$dest"
}

legacy_notice() {
    echo "Legacy claude-switch data detected at $(pretty_path "$LEGACY_BACKUP_DIR")."
    echo "Run 'claude-switch import-legacy' to migrate it into v2."
}

ensure_v2_ready_or_notice() {
    if manifest_exists; then
        manifest_assert_valid || return 1
        return 0
    fi
    if legacy_state_exists; then
        legacy_notice
        return 1
    fi
    manifest_init_empty
    return 0
}

legacy_importable_accounts() {
    jq -r '.sequence[]' "$LEGACY_SEQUENCE_FILE"
}

command_import_legacy() {
    local legacy_number email alias_name uuid account_id config_rel profile_rel config_dest profile_dest legacy_config
    local warnings=()

    check_command_backend_requirements "import-legacy" || return 1

    if ! legacy_state_exists; then
        error "No legacy claude-switch state found at $LEGACY_BACKUP_DIR"
        return 1
    fi

    state_dirs_init
    if manifest_exists && [[ "$(manifest_account_count)" -gt 0 ]]; then
        error "v2 state already contains accounts. Remove $(pretty_path "$STATE_DIR") first if you want to re-import."
        return 1
    fi
    manifest_init_empty

    while IFS= read -r legacy_number; do
        email=$(jq -r --arg num "$legacy_number" '.accounts[$num].email // empty' "$LEGACY_SEQUENCE_FILE")
        alias_name=$(jq -r --arg num "$legacy_number" '.accounts[$num].alias // empty' "$LEGACY_SEQUENCE_FILE")
        uuid=$(jq -r --arg num "$legacy_number" '.accounts[$num].uuid // empty' "$LEGACY_SEQUENCE_FILE")
        if [[ -z "$email" ]]; then
            warnings+=("Skipped legacy account $legacy_number with no email")
            continue
        fi

        account_id="legacy-${legacy_number}-$(sanitize_slug "$email")"
        config_rel="configs/${account_id}.json"
        profile_rel="profiles/${account_id}-$(sanitize_slug "$email")"
        config_dest="$STATE_DIR/$config_rel"
        profile_dest="$STATE_DIR/$profile_rel"
        legacy_config="$LEGACY_BACKUP_DIR/configs/.claude-config-${legacy_number}-${email}.json"

        if [[ ! -f "$legacy_config" ]]; then
            warnings+=("Imported $email without a config snapshot")
        else
            copy_json_file_secure "$legacy_config" "$config_dest" || return 1
        fi
        copy_tree_secure "$(legacy_profile_dir_for "$legacy_number" "$email")" "$profile_dest"
        state_add_account_record "$account_id" "$email" "$uuid" "$alias_name" "$config_rel" "$profile_rel" "legacy:${legacy_number}" || return 1

        local creds
        creds=$(legacy_account_credentials_read "$legacy_number" "$email")
        if [[ -n "$creds" ]]; then
            stored_account_credentials_write "$account_id" "$email" "$creds" || return 1
        else
            warnings+=("Imported $email without stored credentials")
        fi
    done < <(legacy_importable_accounts)

    local active_legacy active_id now
    active_legacy=$(jq -r '.activeAccountNumber // empty' "$LEGACY_SEQUENCE_FILE")
    if [[ -n "$active_legacy" && "$active_legacy" != "null" ]]; then
        active_id="legacy-${active_legacy}-$(sanitize_slug "$(jq -r --arg num "$active_legacy" '.accounts[$num].email // empty' "$LEGACY_SEQUENCE_FILE")")"
        state_set_active_account "$active_id" || true
    fi

    now=$(iso8601_now)
    # shellcheck disable=SC2016  # jq filter references $now via --arg, not shell expansion
    state_write_manifest_jq --arg now "$now" '
        .importedLegacy = true |
        .lastUpdated = $now
    '

    echo "Imported $(manifest_account_count) account(s) from legacy state."
    if [[ ${#warnings[@]} -gt 0 ]]; then
        local warning
        for warning in "${warnings[@]}"; do
            warn "$warning"
        done
    fi
    return 0
}

check_command_backend_requirements() {
    local command_name="$1"
    case "$command_name" in
        help|version|install|uninstall)
            return 0
            ;;
    esac
    require_command jq || return 1
    backend_requirements_for "$command_name" || return 1
    return 0
}

register_current_global_account() {
    local alias_name="${1:-}"
    local current_email current_creds account_id config_rel profile_rel uuid other_id existing_id existing_alias

    ensure_v2_ready_or_notice || return 1
    check_command_backend_requirements "add" || return 1

    if [[ -n "$alias_name" ]] && ! validate_alias "$alias_name"; then
        error "Invalid alias '$alias_name'. Must be alphanumeric/hyphens/underscores, cannot be purely numeric or an email."
        return 1
    fi

    current_email=$(read_current_global_email)
    if [[ "$current_email" == "none" ]]; then
        error "No active Claude account found. Please finish Claude authentication first."
        return 1
    fi

    existing_id=$(state_find_account_id "$current_email")
    if [[ -n "$existing_id" ]]; then
        if [[ -n "$alias_name" ]]; then
            other_id=$(state_alias_in_use_by_other "$alias_name" "$existing_id")
            if [[ -n "$other_id" ]]; then
                error "Alias '$alias_name' is already used by $(state_account_email "$other_id")"
                return 1
            fi
            existing_alias=$(state_account_alias "$existing_id")
            if [[ "$existing_alias" != "$alias_name" ]]; then
                state_set_alias "$existing_id" "$alias_name" || return 1
                echo "Account $current_email is already managed."
                echo "Set alias '$alias_name' for $current_email"
                return 0
            fi
        fi
        echo "Account $current_email is already managed."
        return 0
    fi

    current_creds=$(global_credentials_read)
    if [[ -z "$current_creds" ]]; then
        error "No credentials found for the active Claude account."
        return 1
    fi

    if [[ -n "$alias_name" ]]; then
        other_id=$(state_alias_in_use_by_other "$alias_name" "")
        if [[ -n "$other_id" ]]; then
            error "Alias '$alias_name' is already used by $(state_account_email "$other_id")"
            return 1
        fi
    fi

    account_id=$(generate_account_id "$current_email")
    config_rel="configs/${account_id}.json"
    profile_rel="profiles/${account_id}-$(sanitize_slug "$current_email")"
    uuid=$(current_oauth_uuid)

    save_account_config_snapshot "$(get_claude_config_path)" "$STATE_DIR/$config_rel" || return 1
    stored_account_credentials_write "$account_id" "$current_email" "$current_creds" || return 1
    state_add_account_record "$account_id" "$current_email" "$uuid" "$alias_name" "$config_rel" "$profile_rel" "" || return 1

    echo "Added account: $current_email"
    if [[ -n "$alias_name" ]]; then
        echo "Alias: $alias_name"
    fi
    return 0
}

command_add() {
    local expected_email="${1:-}"
    local alias_name="${2:-}"
    local before_email after_email rerun_hint

    if [[ $# -lt 1 || $# -gt 2 ]]; then
        error "Usage: claude-switch add <email> [alias]"
        return 1
    fi
    if ! validate_email "$expected_email"; then
        error "Invalid email '$expected_email'"
        return 1
    fi
    if [[ -n "$alias_name" ]] && ! validate_alias "$alias_name"; then
        error "Invalid alias '$alias_name'. Must be alphanumeric/hyphens/underscores, cannot be purely numeric or an email."
        return 1
    fi
    rerun_hint="claude-switch add $expected_email"
    if [[ -n "$alias_name" ]]; then
        rerun_hint+=" $alias_name"
    fi

    ensure_v2_ready_or_notice || return 1
    check_command_backend_requirements "add" || return 1
    if ! command -v claude >/dev/null 2>&1; then
        error "'claude' command not found on PATH"
        return 1
    fi
    before_email=$(read_current_global_email)
    refresh_current_managed_snapshot || return 1

    if [[ "$before_email" != "none" ]]; then
        echo "Signing out Claude Code from $before_email to force re-authentication..."
        if ! claude auth logout; then
            error "Claude Code logout failed."
            return 1
        fi
    fi

    echo "Starting Claude Code login..."
    echo "Finish signing in as $expected_email."
    echo "If the browser shows an Authentication Code, copy it and paste it back into this terminal."
    if ! claude auth login --claudeai; then
        error "Claude Code login did not complete successfully."
        return 1
    fi

    after_email=$(read_current_global_email)
    if [[ "$after_email" == "none" ]]; then
        error "No active Claude account found after authentication."
        echo "Complete sign-in as $expected_email, then run '$rerun_hint' again." >&2
        return 1
    fi
    if [[ "$after_email" != "$expected_email" ]]; then
        error "Authenticated as $after_email, but expected $expected_email."
        if [[ "$before_email" != "none" && "$after_email" == "$before_email" ]]; then
            echo "The browser likely reused your existing Claude session." >&2
        fi
        echo "Sign out or switch accounts in Claude, then run '$rerun_hint' again." >&2
        return 1
    fi
    if state_account_exists_by_email "$after_email"; then
        error "Account $after_email is already managed."
        if [[ -n "$alias_name" ]]; then
            echo "Use 'claude-switch alias $after_email ${alias_name}' to rename it." >&2
        fi
        return 1
    fi

    register_current_global_account "$alias_name"
}

command_list() {
    ensure_v2_ready_or_notice || return 1
    echo "Accounts:"
    if [[ "$(manifest_account_count)" -eq 0 ]]; then
        echo "  (none)"
        return 0
    fi
    state_list_render
}

command_alias() {
    local identifier="$1"
    local alias_name="$2"
    local account_id other_id

    ensure_v2_ready_or_notice || return 1
    if ! validate_alias "$alias_name"; then
        error "Invalid alias '$alias_name'. Must be alphanumeric/hyphens/underscores, cannot be purely numeric or an email."
        return 1
    fi

    account_id=$(state_find_account_id "$identifier")
    if [[ -z "$account_id" ]]; then
        error "No account found matching: $identifier"
        return 1
    fi

    other_id=$(state_alias_in_use_by_other "$alias_name" "$account_id")
    if [[ -n "$other_id" ]]; then
        error "Alias '$alias_name' is already used by $(state_account_email "$other_id")"
        return 1
    fi

    state_set_alias "$account_id" "$alias_name" || return 1
    echo "Set alias '$alias_name' for $(state_account_email "$account_id")"
}

command_unalias() {
    local alias_name="$1"
    local account_id

    ensure_v2_ready_or_notice || return 1
    account_id=$(jq -r --arg alias "$alias_name" '.accounts | to_entries[] | select(.value.alias == $alias) | .key' "$MANIFEST_FILE" 2>/dev/null | head -n1)
    if [[ -z "$account_id" || "$account_id" == "null" ]]; then
        error "No account found with alias: $alias_name"
        return 1
    fi

    state_remove_alias "$account_id" || return 1
    echo "Removed alias from $(state_account_email "$account_id")"
}

command_remove_account() {
    local identifier="$1"
    local account_id email config_path profile_path

    ensure_v2_ready_or_notice || return 1
    check_command_backend_requirements "remove" || return 1

    account_id=$(state_find_account_id "$identifier")
    if [[ -z "$account_id" ]]; then
        error "No account found matching: $identifier"
        return 1
    fi

    email=$(state_account_email "$account_id")
    if [[ "$GLOBAL_YES" != true ]]; then
        if ! prompt_yes_no "Permanently remove $email?"; then
            echo "Cancelled"
            return 0
        fi
    fi

    stored_account_credentials_delete "$account_id" "$email"
    config_path=$(state_account_config_path "$account_id")
    profile_path=$(state_account_profile_path "$account_id")
    rm -f "$config_path"
    rm -rf "$profile_path"
    state_remove_account_record "$account_id" || return 1
    echo "$email has been removed"
}

refresh_current_managed_snapshot() {
    local current_email current_id current_creds current_config

    current_email=$(read_current_global_email)
    if [[ "$current_email" == "none" ]]; then
        return 0
    fi
    current_id=$(state_find_account_id "$current_email")
    if [[ -z "$current_id" ]]; then
        return 0
    fi

    current_creds=$(global_credentials_read)
    if [[ -n "$current_creds" ]]; then
        stored_account_credentials_write "$current_id" "$current_email" "$current_creds" || return 1
    fi
    current_config=$(get_claude_config_path)
    if [[ -f "$current_config" ]]; then
        save_account_config_snapshot "$current_config" "$(state_account_config_path "$current_id")" || return 1
    fi
    return 0
}

command_switch() {
    local identifier="$1"
    local account_id email creds target_config oauth_section merged_config

    ensure_v2_ready_or_notice || return 1
    check_command_backend_requirements "switch" || return 1

    account_id=$(state_find_account_id "$identifier")
    if [[ -z "$account_id" ]]; then
        error "No account found matching: $identifier"
        return 1
    fi

    refresh_current_managed_snapshot || return 1

    email=$(state_account_email "$account_id")
    creds=$(stored_account_credentials_read "$account_id" "$email")
    if [[ -z "$creds" ]]; then
        error "No stored credentials found for $email"
        return 1
    fi
    target_config=$(state_account_config_path "$account_id")
    if [[ ! -f "$target_config" ]]; then
        error "Missing config snapshot for $email"
        return 1
    fi

    global_credentials_write "$creds" || return 1
    oauth_section=$(jq '.oauthAccount' "$target_config" 2>/dev/null)
    if [[ -z "$oauth_section" || "$oauth_section" == "null" ]]; then
        error "Invalid oauthAccount in $target_config"
        return 1
    fi
    if [[ -f "$(get_claude_config_path)" ]] && validate_json_file "$(get_claude_config_path)"; then
        merged_config=$(jq --argjson oauth "$oauth_section" '.oauthAccount = $oauth' "$(get_claude_config_path)" 2>/dev/null) || {
            error "Failed to merge target auth into current config"
            return 1
        }
    else
        merged_config=$(<"$target_config")
    fi
    write_json "$(get_claude_config_path)" "$merged_config" || return 1
    state_set_active_account "$account_id" || return 1

    echo "Updated global Claude auth to $email"
    echo "Please restart Claude Desktop or Claude Code to use the new authentication."
}

profile_email_for_dir() {
    local profile_dir="$1"
    local config_file="$profile_dir/.claude.json"
    if [[ ! -f "$config_file" ]]; then
        echo ""
        return 0
    fi
    if ! validate_json_file "$config_file"; then
        error "Invalid JSON in $config_file"
        return 1
    fi
    jq -r '.oauthAccount.emailAddress // empty' "$config_file"
}

command_run() {
    local identifier="$1"
    shift
    local include_local=true
    local claude_args=()
    local account_id email profile_dir before_email after_email setting_sources claude_status=0

    ensure_v2_ready_or_notice || return 1

    if ! command -v claude >/dev/null 2>&1; then
        error "'claude' command not found on PATH"
        return 1
    fi

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --include-local-settings)
                include_local=true
                shift
                ;;
            --exclude-local-settings)
                include_local=false
                shift
                ;;
            --)
                shift
                claude_args=("$@")
                break
                ;;
            *)
                error "Unknown option for run: $1"
                return 1
                ;;
        esac
    done

    account_id=$(state_find_account_id "$identifier")
    if [[ -z "$account_id" ]]; then
        error "No account found matching: $identifier"
        return 1
    fi

    email=$(state_account_email "$account_id")
    profile_dir=$(state_account_profile_path "$account_id")
    ensure_dir_secure "$profile_dir"
    link_shared_user_scope_into_profile "$profile_dir"
    link_current_project_memory_into_profile "$profile_dir"

    before_email=$(profile_email_for_dir "$profile_dir") || return 1
    if [[ -n "$before_email" && "$before_email" != "$email" ]]; then
        error "Profile at $profile_dir is authenticated as $before_email, expected $email."
        echo "Remediation: remove that profile directory or run:" >&2
        echo "  CLAUDE_CONFIG_DIR=\"$profile_dir\" claude auth logout" >&2
        return 1
    fi
    if [[ -z "$before_email" ]]; then
        echo "First run for $email."
        echo "The claude CLI will use an isolated profile at $profile_dir."
        echo "This does not change the global Claude config used by Claude Desktop."
        echo "When prompted, sign in as $email."
    fi

    setting_sources="user,project"
    if [[ "$include_local" == true ]]; then
        setting_sources="user,project,local"
    fi

    if CLAUDE_CONFIG_DIR="$profile_dir" command claude --setting-sources "$setting_sources" "${claude_args[@]}"; then
        claude_status=0
    else
        claude_status=$?
    fi

    after_email=$(profile_email_for_dir "$profile_dir") || return 1
    if [[ -n "$after_email" && "$after_email" != "$email" ]]; then
        warn "Profile at $profile_dir is now authenticated as $after_email, expected $email."
        echo "Remediation: remove that profile directory or run:" >&2
        echo "  CLAUDE_CONFIG_DIR=\"$profile_dir\" claude auth logout" >&2
        return 2
    fi

    return "$claude_status"
}

progress_bar() {
    local pct="${1%.*}"
    local width=20
    local filled=$(( pct * width / 100 ))
    local empty=$(( width - filled ))
    local bar=""
    local i
    for ((i=0; i<filled; i++)); do bar+="#"; done
    for ((i=0; i<empty; i++)); do bar+="."; done
    printf '%s %3d%%' "$bar" "$pct"
}

show_usage_metrics() {
    local creds token response now five_util five_reset seven_util seven_reset five_bar seven_bar five_epoch seven_epoch five_msg="" seven_msg=""

    if ! command -v curl >/dev/null 2>&1; then
        return 0
    fi
    creds=$(global_credentials_read)
    if [[ -z "$creds" ]]; then
        return 0
    fi
    token=$(jq -r '.claudeAiOauth.accessToken // empty' <<< "$creds" 2>/dev/null)
    if [[ -z "$token" ]]; then
        return 0
    fi

    spinner_start "Fetching usage..."
    response=$(curl -s --max-time 5 \
        -H "Authorization: Bearer $token" \
        -H "anthropic-beta: oauth-2025-04-20" \
        "https://api.anthropic.com/api/oauth/usage" 2>/dev/null)
    spinner_stop

    if [[ -z "$response" ]] || ! jq -e '.five_hour' <<< "$response" >/dev/null 2>&1; then
        return 0
    fi

    now=$(date +%s)
    five_util=$(jq -r '.five_hour.utilization // 0' <<< "$response")
    five_reset=$(jq -r '.five_hour.resets_at // empty' <<< "$response")
    seven_util=$(jq -r '.seven_day.utilization // 0' <<< "$response")
    seven_reset=$(jq -r '.seven_day.resets_at // empty' <<< "$response")

    if [[ -n "$five_reset" ]]; then
        five_epoch=$(parse_reset_time_epoch "$five_reset")
        if [[ -n "$five_epoch" ]]; then
            five_msg="  resets in $(format_duration $((five_epoch - now)))"
        fi
    fi
    if [[ -n "$seven_reset" ]]; then
        seven_epoch=$(parse_reset_time_epoch "$seven_reset")
        if [[ -n "$seven_epoch" ]]; then
            seven_msg="  resets in $(format_duration $((seven_epoch - now)))"
        fi
    fi

    five_bar=$(progress_bar "$five_util")
    seven_bar=$(progress_bar "$seven_util")

    echo "Usage:"
    echo "  5-hour: $five_bar$five_msg"
    echo "  7-day:  $seven_bar$seven_msg"
}

command_status() {
    local current_email account_id alias_name

    ensure_v2_ready_or_notice || return 1
    check_command_backend_requirements "status" || return 1

    current_email=$(read_current_global_email)
    if [[ "$current_email" == "none" ]]; then
        echo "No active Claude account found."
        return 0
    fi

    echo "Account: $current_email"
    account_id=$(state_find_account_id "$current_email")
    if [[ -n "$account_id" ]]; then
        alias_name=$(state_account_alias "$account_id")
        if [[ -n "$alias_name" ]]; then
            echo "Alias:   $alias_name"
        fi
    else
        echo "(not managed)"
    fi

    show_usage_metrics
}

script_version_from_file() {
    local file="$1"
    sed -n 's/^readonly VERSION="\([^"]*\)".*/\1/p' "$file" | head -n1
}

claude_switch_download_update() {
    local dest="$1"
    local update_url="${CLAUDE_SWITCH_UPDATE_URL:-}"
    local release_ref api_response

    require_command curl || return 1

    if [[ -n "$update_url" ]]; then
        curl -fsSL "$update_url" -o "$dest" || {
            error "Failed to download update from $update_url"
            return 1
        }
        return 0
    fi

    api_response=$(curl -fsSL "$UPDATE_RELEASE_API_URL") || {
        error "Failed to query the latest claude-switch release"
        return 1
    }

    release_ref=$(jq -r '.tag_name // empty' <<< "$api_response")
    if [[ -z "$release_ref" ]]; then
        error "Latest release metadata did not include a tag name"
        return 1
    fi

    update_url="https://raw.githubusercontent.com/${UPDATE_REPO_OWNER}/${UPDATE_REPO_NAME}/${release_ref}/claude-switch.sh"
    curl -fsSL "$update_url" -o "$dest" || {
        error "Failed to download claude-switch release $release_ref"
        return 1
    }
}

command_update() {
    local install_dir=""
    local binary_name="claude-switch"
    local source_file="${BASH_SOURCE[0]}"
    local target_file target_dir downloaded_file downloaded_version current_version

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --prefix)
                if [[ $# -lt 2 ]]; then
                    error "--prefix requires a path argument"
                    return 1
                fi
                install_dir="$2"
                shift 2
                ;;
            *)
                error "Unknown option '$1'"
                return 1
                ;;
        esac
    done

    source_file="$(cd "$(dirname "$source_file")" && pwd)/$(basename "$source_file")"
    if [[ -n "$install_dir" ]]; then
        target_file="$install_dir/$binary_name"
        if [[ ! -f "$target_file" ]]; then
            error "$binary_name not found at $target_file"
            return 1
        fi
    else
        target_file="$source_file"
    fi
    target_dir="$(dirname "$target_file")"

    downloaded_file=$(mktemp "${TMPDIR:-/tmp}/claude-switch-update.XXXXXX")
    if ! claude_switch_download_update "$downloaded_file"; then
        rm -f "$downloaded_file"
        return 1
    fi
    if ! bash -n "$downloaded_file"; then
        rm -f "$downloaded_file"
        error "Downloaded update is not a valid Bash script"
        return 1
    fi

    downloaded_version=$(script_version_from_file "$downloaded_file")
    current_version=$(script_version_from_file "$target_file")
    if [[ -z "$downloaded_version" ]]; then
        rm -f "$downloaded_file"
        error "Downloaded update did not contain a version header"
        return 1
    fi

    if [[ -n "$current_version" && "$downloaded_version" == "$current_version" ]]; then
        rm -f "$downloaded_file"
        echo "claude-switch is already up to date ($current_version)"
        return 0
    fi

    echo "Updating claude-switch at $target_file"
    if [[ -n "$current_version" ]]; then
        echo "Current version: $current_version"
    fi
    echo "New version:     $downloaded_version"
    run_maybe_sudo "$target_dir" cp "$downloaded_file" "$target_file"
    run_maybe_sudo "$target_dir" chmod +x "$target_file"
    rm -f "$downloaded_file"
    echo "Successfully updated claude-switch to $downloaded_version"
}

command_install() {
    local install_dir="/usr/local/bin"
    local binary_name="claude-switch"
    local source_file="${BASH_SOURCE[0]}"
    local platform

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --prefix)
                if [[ $# -lt 2 ]]; then
                    error "--prefix requires a path argument"
                    return 1
                fi
                install_dir="$2"
                shift 2
                ;;
            *)
                error "Unknown option '$1'"
                return 1
                ;;
        esac
    done

    source_file="$(cd "$(dirname "$source_file")" && pwd)/$(basename "$source_file")"
    platform=$(detect_platform)
    echo "Platform: $platform"

    if ! command -v jq >/dev/null 2>&1; then
        warn "jq is not installed. claude-switch requires jq to run."
    fi
    if [[ "$platform" == "linux" ]] && ! command -v secret-tool >/dev/null 2>&1; then
        warn "secret-tool is not installed. Required for secure credential storage."
    fi
    if [[ "$platform" == "wsl" ]] && ! command -v powershell.exe >/dev/null 2>&1; then
        warn "powershell.exe is not accessible. Required for secure credential storage."
    fi

    if [[ ! -d "$install_dir" ]]; then
        run_maybe_sudo "$(dirname "$install_dir")" mkdir -p "$install_dir"
    fi

    local dest="$install_dir/$binary_name"
    echo "Installing $binary_name to $dest"
    run_maybe_sudo "$install_dir" cp "$source_file" "$dest"
    run_maybe_sudo "$install_dir" chmod +x "$dest"

    case ":$PATH:" in
        *":$install_dir:"*) ;;
        *) warn "$install_dir is not on your PATH." ;;
    esac

    echo "Successfully installed $binary_name to $dest"
}

command_uninstall() {
    local install_dir="/usr/local/bin"
    local binary_name="claude-switch"
    local dest

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --prefix)
                if [[ $# -lt 2 ]]; then
                    error "--prefix requires a path argument"
                    return 1
                fi
                install_dir="$2"
                shift 2
                ;;
            *)
                error "Unknown option '$1'"
                return 1
                ;;
        esac
    done

    dest="$install_dir/$binary_name"
    if [[ ! -f "$dest" ]]; then
        error "$binary_name not found at $dest"
        return 1
    fi

    echo "Removing $dest"
    run_maybe_sudo "$install_dir" rm "$dest"
    echo "Removed $dest"

    if [[ -d "$STATE_DIR" ]]; then
        local confirm="n"
        if [[ "$GLOBAL_YES" == true ]]; then
            confirm="y"
        else
            echo -n "Also remove v2 state ($STATE_DIR)? [y/N] "
            read -r confirm
        fi
        if [[ "$confirm" == "y" || "$confirm" == "Y" ]]; then
            rm -rf "$STATE_DIR"
            echo "Removed $STATE_DIR"
        fi
    fi

    echo "Successfully uninstalled $binary_name"
}

should_start_interactive_launcher() {
    if [[ "$INTERACTIVE_FORCE" == "1" ]]; then
        return 0
    fi
    [[ -t 0 && -t 1 ]]
}

launcher_supports_color() {
    [[ -t 1 ]] || return 1
    [[ -z "${NO_COLOR:-}" ]] || return 1
    [[ "${TERM:-}" != "dumb" ]]
}

launcher_theme_init() {
    if launcher_supports_color; then
        LAUNCHER_RESET=$'\033[0m'
        LAUNCHER_BOLD=$'\033[1m'
        LAUNCHER_TITLE=$'\033[38;2;210;216;224m'
        LAUNCHER_MUTED=$'\033[38;2;126;136;149m'
        LAUNCHER_LINE=$'\033[38;2;74;84;100m'
        LAUNCHER_ACCENT=$'\033[38;2;168;180;197m'
        LAUNCHER_ACCENT_ALT=$'\033[38;2;144;156;174m'
        LAUNCHER_ACTIVE=$'\033[38;2;228;233;239m'
    else
        LAUNCHER_RESET=""
        LAUNCHER_BOLD=""
        LAUNCHER_TITLE=""
        LAUNCHER_MUTED=""
        LAUNCHER_LINE=""
        LAUNCHER_ACCENT=""
        LAUNCHER_ACCENT_ALT=""
        LAUNCHER_ACTIVE=""
    fi
}

launcher_layout_init() {
    local cols
    cols="${COLUMNS:-}"
    if [[ -z "$cols" ]] && command -v tput >/dev/null 2>&1; then
        cols=$(tput cols 2>/dev/null || echo "")
    fi
    if [[ -z "$cols" || "$cols" -lt 68 ]]; then
        cols=96
    fi

    LAUNCHER_WIDTH=$((cols - 4))
    if [[ "$LAUNCHER_WIDTH" -gt 100 ]]; then
        LAUNCHER_WIDTH=100
    fi
    if [[ "$LAUNCHER_WIDTH" -lt 64 ]]; then
        LAUNCHER_WIDTH=64
    fi

    LAUNCHER_INNER_WIDTH=$((LAUNCHER_WIDTH - 2))
    LAUNCHER_MARGIN=$(((cols - LAUNCHER_WIDTH) / 2))
    if [[ "$LAUNCHER_MARGIN" -lt 0 ]]; then
        LAUNCHER_MARGIN=0
    fi
}

launcher_repeat() {
    local char="$1"
    local count="$2"
    local out=""
    while [[ "${#out}" -lt "$count" ]]; do
        out+="$char"
    done
    printf '%s' "${out:0:$count}"
}

launcher_trim() {
    local text="$1"
    local width="$2"
    if [[ "${#text}" -le "$width" ]]; then
        printf '%s' "$text"
        return 0
    fi
    if [[ "$width" -le 3 ]]; then
        printf '%s' "${text:0:$width}"
        return 0
    fi
    printf '%s...' "${text:0:$((width - 3))}"
}

launcher_margin_pad() {
    printf '%*s' "$LAUNCHER_MARGIN" ""
}

launcher_frame_top() {
    printf '%s%b┌%s┐%b\n' \
        "$(launcher_margin_pad)" \
        "$LAUNCHER_LINE" \
        "$(launcher_repeat '─' "$LAUNCHER_INNER_WIDTH")" \
        "$LAUNCHER_RESET"
}

launcher_frame_bottom() {
    printf '%s%b└%s┘%b\n' \
        "$(launcher_margin_pad)" \
        "$LAUNCHER_LINE" \
        "$(launcher_repeat '─' "$LAUNCHER_INNER_WIDTH")" \
        "$LAUNCHER_RESET"
}

launcher_frame_row() {
    local text="$1"
    local align="${2:-left}"
    local tone="${3:-}"
    local plain pad left_pad right_pad padded

    plain=$(launcher_trim "$text" "$LAUNCHER_INNER_WIDTH")
    pad=$((LAUNCHER_INNER_WIDTH - ${#plain}))
    left_pad=0
    right_pad="$pad"

    if [[ "$align" == "center" ]]; then
        left_pad=$((pad / 2))
        right_pad=$((pad - left_pad))
    fi

    padded="$(printf '%*s%s%*s' "$left_pad" '' "$plain" "$right_pad" '')"
    printf '%s%b│%b%b%s%b%b│%b\n' \
        "$(launcher_margin_pad)" \
        "$LAUNCHER_LINE" "$LAUNCHER_RESET" \
        "$tone" "$padded" "$LAUNCHER_RESET" \
        "$LAUNCHER_LINE" "$LAUNCHER_RESET"
}

launcher_frame_empty() {
    launcher_frame_row ""
}

launcher_box_top() {
    local width="$1"
    local title="$2"
    local body label filler left_fill right_fill

    body=$((width - 2))
    label=" $title "
    if [[ "${#label}" -gt "$body" ]]; then
        label=" $(launcher_trim "$title" "$((body - 2))") "
    fi
    filler=$((body - ${#label}))
    left_fill=$((filler / 2))
    right_fill=$((filler - left_fill))
    printf '┌%s%s%s┐' \
        "$(launcher_repeat '─' "$left_fill")" \
        "$label" \
        "$(launcher_repeat '─' "$right_fill")"
}

launcher_box_bottom() {
    local width="$1"
    printf '└%s┘' "$(launcher_repeat '─' "$((width - 2))")"
}

launcher_box_row() {
    local width="$1"
    local text="$2"
    local body plain right_pad

    body=$((width - 4))
    plain=$(launcher_trim "$text" "$body")
    right_pad=$((body - ${#plain}))
    printf '│ %s%*s │' "$plain" "$right_pad" ''
}

launcher_box_rule() {
    local width="$1"
    printf '│ %s │' "$(launcher_repeat '─' "$((width - 4))")"
}

launcher_prompt() {
    printf '%b›%b ' "$LAUNCHER_TITLE$LAUNCHER_BOLD" "$LAUNCHER_RESET"
}

launcher_status_line() {
    local managed_count workspace
    managed_count=$(manifest_account_count)
    workspace=$(pretty_path "$(pwd)")
    printf '%s%bclaude-switch v%s%b %b•%b %s profile%s %b•%b %s\n' \
        "$(launcher_margin_pad)" \
        "$LAUNCHER_MUTED" "$VERSION" "$LAUNCHER_RESET" \
        "$LAUNCHER_LINE" "$LAUNCHER_RESET" \
        "$managed_count" "$( [[ "$managed_count" == "1" ]] && echo "" || echo "s" )" \
        "$LAUNCHER_LINE" "$LAUNCHER_RESET" \
        "$workspace"
}

launcher_show_summary_box() {
    local current_email="$1"
    local managed_count="$2"
    local platform_name="$3"
    local workspace="$4"
    local box_width

    box_width=$((LAUNCHER_INNER_WIDTH - 22))
    if [[ "$box_width" -gt 62 ]]; then
        box_width=62
    fi
    if [[ "$box_width" -lt 42 ]]; then
        box_width=$((LAUNCHER_INNER_WIDTH - 4))
    fi

    launcher_frame_row "$(launcher_box_top "$box_width" "session")" center "$LAUNCHER_LINE"
    launcher_frame_row "$(launcher_box_row "$box_width" "desktop   $current_email")" center
    launcher_frame_row "$(launcher_box_row "$box_width" "profiles  $managed_count managed")" center
    launcher_frame_row "$(launcher_box_row "$box_width" "platform  $platform_name")" center
    launcher_frame_row "$(launcher_box_row "$box_width" "workspace $workspace")" center
    launcher_frame_row "$(launcher_box_bottom "$box_width")" center "$LAUNCHER_LINE"
}

launcher_show_accounts() {
    local box_width active_id rows idx

    box_width=$((LAUNCHER_INNER_WIDTH - 10))
    if [[ "$box_width" -lt 56 ]]; then
        box_width=$((LAUNCHER_INNER_WIDTH - 4))
    fi

    launcher_frame_row "$(launcher_box_top "$box_width" "managed profiles")" center "$LAUNCHER_LINE"

    if ! manifest_exists || [[ "$(manifest_account_count)" -eq 0 ]]; then
        launcher_frame_row "$(launcher_box_row "$box_width" "no managed profiles yet")" center "$LAUNCHER_TITLE"
        launcher_frame_row "$(launcher_box_row "$box_width" "start with: add you@example.com work")" center "$LAUNCHER_MUTED"
        launcher_frame_row "$(launcher_box_bottom "$box_width")" center "$LAUNCHER_LINE"
        return 0
    fi

    active_id=$(state_current_active_managed_id)
    mapfile -t rows < <(
        jq -r --arg active "$active_id" '
            .order[] as $id |
            .accounts[$id] |
            [
                (if $id == $active then "1" else "0" end),
                .email,
                (.alias // "")
            ] | @tsv
        ' "$MANIFEST_FILE"
    )

    for idx in "${!rows[@]}"; do
        local row_active email alias_name profile_title target state_label action_line detail_tone
        IFS=$'\t' read -r row_active email alias_name <<< "${rows[$idx]}"

        profile_title="$email"
        target="$email"
        if [[ -n "$alias_name" ]]; then
            profile_title="$alias_name"
            target="$alias_name"
        fi

        state_label="isolated profile"
        detail_tone="$LAUNCHER_MUTED"
        if [[ "$row_active" == "1" ]]; then
            state_label="desktop default"
            detail_tone="$LAUNCHER_ACCENT"
        fi

        action_line="$state_label • run $target • switch $target"
        launcher_frame_row "$(launcher_box_row "$box_width" "$profile_title")" center "$LAUNCHER_ACTIVE"
        if [[ -n "$alias_name" ]]; then
            launcher_frame_row "$(launcher_box_row "$box_width" "$email")" center "$LAUNCHER_MUTED"
        fi
        launcher_frame_row "$(launcher_box_row "$box_width" "$action_line")" center "$detail_tone"
        if [[ "$idx" -lt $((${#rows[@]} - 1)) ]]; then
            launcher_frame_row "$(launcher_box_rule "$box_width")" center "$LAUNCHER_LINE"
        fi
    done

    launcher_frame_row "$(launcher_box_bottom "$box_width")" center "$LAUNCHER_LINE"
}

launcher_show_banner() {
    local current_email managed_count platform_name workspace

    launcher_theme_init
    launcher_layout_init
    clear_screen
    current_email=$(read_current_global_email)
    if [[ "$current_email" == "none" ]]; then
        current_email="unmanaged"
    fi
    managed_count=$(manifest_account_count)
    platform_name=$(detect_platform)
    workspace=$(pretty_path "$(pwd)")

    launcher_frame_top
    launcher_frame_empty
    launcher_frame_row "claude-switch." center "$LAUNCHER_TITLE$LAUNCHER_BOLD"
    launcher_frame_row "launch Claude profiles from one terminal" center "$LAUNCHER_ACCENT"
    launcher_frame_row "$workspace" center "$LAUNCHER_MUTED"
    launcher_frame_empty
    launcher_show_summary_box "$current_email" "$managed_count" "$platform_name" "$workspace"
    launcher_frame_empty
    launcher_show_accounts
    launcher_frame_empty
    launcher_frame_row "[add] new account   [run profile] isolate   [switch profile] desktop" center "$LAUNCHER_ACCENT_ALT"
    launcher_frame_row "[list] inspect profiles   [help] reference   [clear] redraw   [q] quit" center "$LAUNCHER_MUTED"
    launcher_frame_bottom
    echo ""
}

launcher_show_help() {
    cat <<'EOF'
Switch:
  add <email> [alias]              Run Claude Code login and add a managed account
  run <email|alias> [-- ...]       Launch the claude CLI in an isolated profile
  switch <email|alias>             Switch the global Claude account

Manage:
  list                             List managed accounts
  alias <email|alias> <name>       Set an alias
  unalias <alias>                  Remove an alias
  remove <email|alias>             Remove an account

Inspect:
  status, whoami                   Show current account info
  import-legacy                    Import legacy ~/.claude-switch-backup data
  install [--prefix /path]         Install claude-switch
  uninstall [--prefix /path]       Uninstall claude-switch
  update [--prefix /path]          Update claude-switch to the latest release
  version                          Show the current version

Launcher:
  help                             Show this help
  clear                            Redraw the launcher
  quit                             Exit claude-switch
  /<command>                       Slash-prefixed commands also work
EOF
}

launcher_offer_legacy_import() {
    LAUNCHER_REDRAW_AFTER_IMPORT=0
    if manifest_exists || ! legacy_state_exists; then
        return 0
    fi
    LAUNCHER_REDRAW_AFTER_IMPORT=1
    echo ""
    echo "Legacy state detected at $(pretty_path "$LEGACY_BACKUP_DIR")."
    if prompt_yes_no "Import it into v2 now?"; then
        command_import_legacy || return 1
        pause_for_enter
    fi
    return 0
}

run_subcommand() {
    local command="$1"
    shift
    case "$command" in
        add) command_add "$@" ;;
        list) command_list "$@" ;;
        run) command_run "$@" ;;
        switch) command_switch "$@" ;;
        status|whoami) command_status ;;
        alias) command_alias "$@" ;;
        unalias) command_unalias "$@" ;;
        remove) command_remove_account "$@" ;;
        install) command_install "$@" ;;
        uninstall) command_uninstall "$@" ;;
        update|upgrade) command_update "$@" ;;
        import-legacy) command_import_legacy "$@" ;;
        version)
            echo "claude-switch $VERSION"
            ;;
        help)
            show_usage
            ;;
        *)
            error "Unknown command '$command'"
            return 1
            ;;
    esac
}

launcher_execute_line() {
    local line="$1"
    local args=()
    local command

    read -r -a args <<< "$line"
    if [[ ${#args[@]} -eq 0 ]]; then
        return 0
    fi

    command="${args[0]}"
    if [[ "$command" == /* ]]; then
        command="${command#/}"
    fi

    case "$command" in
        quit|exit|q)
            return 10
            ;;
        clear|cls)
            launcher_show_banner
            return 0
            ;;
        help)
            launcher_show_help
            return 0
            ;;
        *)
            if run_subcommand "$command" "${args[@]:1}"; then
                return 0
            fi
            local status=$?
            echo ""
            echo "Command exited with status $status."
            return 0
            ;;
    esac
}

command_launcher() {
    launcher_show_banner
    launcher_offer_legacy_import || return 1
    if [[ "${LAUNCHER_REDRAW_AFTER_IMPORT:-0}" == "1" ]]; then
        launcher_show_banner
    fi
    while true; do
        local line
        launcher_status_line
        line=$(prompt_line "$(launcher_prompt)")
        if ! launcher_execute_line "$line"; then
            local status=$?
            if [[ "$status" -eq 10 ]]; then
                echo ""
                return 0
            fi
            return "$status"
        fi
        echo ""
    done
}

legacy_command_hint() {
    local arg="$1"
    case "$arg" in
        --add) echo "claude-switch add <email> [alias]" ;;
        --add-account) echo "claude-switch add <email> [alias]" ;;
        --remove-account) echo "claude-switch remove <email|alias>" ;;
        --list) echo "claude-switch list" ;;
        --run) echo "claude-switch run <email|alias>" ;;
        --switch) echo "claude-switch switch <email|alias>" ;;
        --status|--whoami) echo "claude-switch status" ;;
        --alias) echo "claude-switch alias <email|alias> <name>" ;;
        --unalias) echo "claude-switch unalias <alias>" ;;
        --install) echo "claude-switch install" ;;
        --uninstall) echo "claude-switch uninstall" ;;
        --update|--upgrade) echo "claude-switch update" ;;
        --version) echo "claude-switch version" ;;
        --help) echo "claude-switch help" ;;
        *)
            echo ""
            ;;
    esac
}

show_usage() {
    echo "claude-switch v$VERSION"
    echo "Usage: claude-switch <command> [args]"
    echo ""
    echo "Commands:"
    echo "  add <email> [alias]              Run Claude Code login and add a managed account"
    echo "  list                             List managed accounts"
    echo "  run <email|alias> [-- ...]       Launch the claude CLI in an isolated profile"
    echo "  switch <email|alias>             Switch the global Claude account"
    echo "  status, whoami                   Show current account info"
    echo "  alias <email|alias> <name>       Set an alias"
    echo "  unalias <alias>                  Remove an alias"
    echo "  remove <email|alias>             Remove an account"
    echo "  import-legacy                    Import legacy ~/.claude-switch-backup data"
    echo "  install [--prefix /path]         Install claude-switch"
    echo "  uninstall [--prefix /path]       Uninstall claude-switch"
    echo "  update [--prefix /path]          Update claude-switch to the latest release"
    echo "  version                          Show the current version"
    echo "  help                             Show this help"
    echo ""
    echo "Options:"
    echo "  -y, --yes                        Skip confirmation prompts where supported"
    echo "  --exclude-local-settings         With run, ignore Claude's local repo settings source"
    echo "  --include-local-settings         Accepted for compatibility; local is now included by default"
    echo ""
    echo "Interactive:"
    echo "  Run 'claude-switch' with no arguments in a TTY to open the launcher."
    echo ""
    echo "Examples:"
    echo "  claude-switch"
    echo "  claude-switch add alice@example.com work"
    echo "  claude-switch import-legacy"
    echo "  claude-switch run work -- --model sonnet"
    echo "  claude-switch switch work"
    echo "  claude-switch update"
}

main() {
    local args=()
    local arg command legacy_hint

    for arg in "$@"; do
        case "$arg" in
            -y|--yes)
                GLOBAL_YES=true
                ;;
            *)
                args+=("$arg")
                ;;
        esac
    done
    set -- "${args[@]+"${args[@]}"}"

    # Bootstrap commands must run on systems with stock Bash 3.2 (e.g. macOS),
    # so the Bash 4.4+ gate only applies once we know the command needs it.
    case "${1:-}" in
        help|version|install|uninstall|update|upgrade) ;;
        *) check_bash_version || return 1 ;;
    esac

    if [[ "${1:-}" == --* ]]; then
        legacy_hint=$(legacy_command_hint "$1")
        if [[ -n "$legacy_hint" ]]; then
            error "Legacy flag-style syntax is no longer supported in v2."
            echo "Use: $legacy_hint" >&2
            return 1
        fi
    fi

    if [[ $# -eq 0 ]]; then
        if [[ $EUID -eq 0 ]] && ! in_container && should_start_interactive_launcher; then
            error "Do not run this script as root (unless running in a container)"
            return 1
        fi
        if should_start_interactive_launcher; then
            command_launcher
        else
            show_usage
        fi
        return $?
    fi

    if [[ $EUID -eq 0 ]] && ! in_container; then
        case "$1" in
            help|version|install|uninstall|update|upgrade)
                ;;
            *)
                error "Do not run this script as root (unless running in a container)"
                return 1
                ;;
        esac
    fi

    command="$1"
    shift
    check_command_backend_requirements "$command" || return 1
    run_subcommand "$command" "$@"
}

main "$@"

