#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_FILE="$ROOT_DIR/claude-switch.sh"
MODULES=(
  "$ROOT_DIR/src/00-header.sh"
  "$ROOT_DIR/src/10-common.sh"
  "$ROOT_DIR/src/20-backends.sh"
  "$ROOT_DIR/src/30-store.sh"
  "$ROOT_DIR/src/40-commands.sh"
  "$ROOT_DIR/src/50-launcher.sh"
  "$ROOT_DIR/src/99-main.sh"
)

tmp_file="$(mktemp "$OUT_FILE.XXXXXX")"
trap 'rm -f "$tmp_file"' EXIT

{
  printf '%s\n' "#!/usr/bin/env bash"
  printf '\n'
  printf '%s\n' "# Generated by scripts/build.sh. Edit src/* instead."
  printf '\n'
  for module in "${MODULES[@]}"; do
    sed '1{/^#!\/usr\/bin\/env bash$/d;}' "$module"
    printf '\n'
  done
} > "$tmp_file"

chmod +x "$tmp_file"
mv "$tmp_file" "$OUT_FILE"
